total = 10_000
continues = false

[simulation]
workers = 1
tables = 10
max_time = 1_000
client_ratio = 0.95
production_time = { start = 1, end = 2 }
dancing_time = { start = 1, end = 2 }
consumption_time = { start = 1, end = 2 }
