[simulation]
use_logs = true
max_time = 40_000

workers = 2
tables = 10
client_ratio = 0.85
production_time = { start = 1, end = 3 }
dancing_time = { start = 2, end = 5 }
consumption_time = { start = 1, end = 5 }

[stats]
alpha = 0.05

[experiment]
total = 1_000
continous = true
parameter = "waiting_time"

[scenario]
parameter = "tables"
values = { start = 1, end = 10 } 
step = 1
