[simulation]
use_logs = true
max_time = 10_000

workers = 2
tables = 10
client_ratio = 0.85
production_time = { start = 1, end = 3 }
dancing_time = { start = 2, end = 5 }
consumption_time = { start = 1, end = 5 }

[stats]
alpha = 0.05

[experiment]
total = 1_000
min_total = 300
continous = true
parameter = "waiting_time"
gap_size = 1000


# [[scenario.parameters]]
# kind = "tables"
# values = { start = 1, end = 10 } 
# step = 1

[[scenario.parameters]]
kind = "clients"
values = { start = 40, end = 80 } 
step = 5
