total = 1_000
continues = false

[simulation]
workers = 2
tables = 10
max_time = 10_000
client_ratio = 0.65
production_time = { start = 1, end = 3 }
dancing_time = { start = 2, end = 5 }
consumption_time = { start = 1, end = 3 }

[stats]
alpha = 0.05
